src/imageMeasure.js, src/printer.js
I've removed hard-coding to the node_modules path. It was causing issues in a meteor app when packaged with demeteorizer for deployment.
=> Fixed pdfmake to work with demeteorizer

src/tableProcessor.js
=> Bug fix: Vertical line in Rowspans

src/layoutBuilder.js, tests/layoutBuilder.js
=> ADD maxHeight option to text.

src/printer.js
Add links to PDF by doing this: { text:"Google", link:"http://www.google.com", decoration:"underline" }
=> Add ability to turn text into a link

README.md, src/printer.js
I needed the abillity to st pdf metadata, so I looked into the pdfkit api and found a very simple way..
=> changes for setting pdf metadata + doku update

src/textTools.js
This fixed generating links in PDF added by PR #361.
=> Fix for links

webpack.config.js
Fixes slashes in webpack config for build on Windows.
=> Fix for build on Windows

src/elementWriter.js
This should fix #635, #623, #592, #589, #557, #376, #446 etc.
=> Don't add up the images horizontal offset

README.md
=> added sample code to README for showing PDF on the page that created it

src/printer.js
removed 'FontProvider' duplicate declaration in 'printer.js'
=> removed duplicate declaration

.npmignore, build/pdfmake.js, webpack.config.js
Builds a webpack lib and fixes windows build issues.
=> fix webpack and windows build

README.md, src/layoutBuilder.js, tests/layoutBuilder.js
I needed the current page size in a footer to draw some vectors and thought this might be useful to someone else. Please let me know if there is already a way to do this as I couldn't find anything.
=> provide page size to dynamic header and footer functions

package.json
=> chore: move linebreak to dependencies list

src/textTools.js
This fixes https://github.com/bpampuch/pdfmake/issues/842
All tests pass.
=> fix noWrap ignored #842

README.md, src/printer.js, src/textTools.js
internal link feature:
`{ text:"Go to page 2", targetPage: 2 }`
=> internal link

src/layoutBuilder.js, tests/layoutBuilder.js
This prevents items from breaking across different pages.
=> Add `unbreakable` attribute to elements

src/documentContext.js, src/layoutBuilder.js, src/tableProcessor.js, tests/integration/background.js
=> Fix Background image overwrite 'fillColor' on table #437

README.md
Updated documentation about the change from https://github.com/bpampuch/pdfmake/pull/1587
=> Documented new createPdf parameters

examples/vectors.js, src/printer.js
Rectangle had it already, I need it for ellipse too because I want to draw 3D looking shaded cylinder.
=> Add linear gradient to ellipse

src/Renderer.js
Solve #1785 without users having to specify options.
=> Default to points by default

src/LayoutBuilder.js
Removed all Array function callbacks to improve performance greatly when `pageBreakBeforeFct` is defined. Related to https://github.com/bpampuch/pdfmake/issues/1410
=> pageBreakBeforeFct performance improvement

package.json, src/svgMeasure.js, tests/integration/svgs.js, tests/svgMeasure.js
Makes the SVG parsing slightly more robust to address #2021 
Branched from 0.1.66 tag.
=> Fix some problems parsing SVGs

src/Printer.js
=> Change how infos are passed to pdfkit, so the PDF "/ID" is correct

examples/tables.js, src/DocMeasure.js
Related #2148,  I fixed the size of the image in the table.
=> Cover image size inside table

src/TextDecorator.js
Discovered and fixed a typo on unknown decoration
=> Text Decorator typo

src/TableProcessor.js, src/columnCalculator.js, tests/unit/columnCalculator.spec.js
Fixes widths of table columns with percentages (issue [#401](https://github.com/bpampuch/pdfmake/issues/401))
=> Fixes #401
