bpampuch/pdfmake

.editorconfig
README.md
package.json
src/browser-extensions/pdfMake.js
src/docMeasure.js
src/documentContext.js
src/elementWriter.js
src/imageMeasure.js
src/layoutBuilder.js
src/pageElementWriter.js
src/printer.js
src/styleContextStack.js
src/tableProcessor.js
src/textTools.js
tests/docMeasure.js
tests/documentContext.js
tests/elementWriter.js
tests/layoutBuilder.js
tests/pageElementWriter.js
tests/printer.js
tests/tableProcessor.js

This pull request groups several features and bug-fixes. We open it as one pull request, because we want to avoid merge conflicts during development.
Features:
* Introduce new styling properties marginLeft, marginRight, marginTop, and marginBottom.
* Add the capability to have switch of page orientation per page.
* Adds an editorconfig.
* Adding possibility to specify line height.
* Access to internal pages array, to have better testing capabilities.
* Dynamically control page breaks, for instance to avoid orphan childs.
Bug Fixes:
* Add the type to the font name for pdfkit. This is to avoid using the same type (normal, bold, italics, bolditalics) every time a font is requested. Fixes #162.
* Use function for vLineColor if provided on table layout. Fixes #166.
An element in the document …

Several new features & bugfixes

---

bower.json

adding the vfs_fonts.js to main enables grunt to add it to index.html when running 'grunt wiredep'

adding the vfs_fonts.js to "main"

---

Gruntfile.js
src/fontProvider.js
src/fontWrapper.js
src/printer.js
tests/fontWrapper.js
tests/printer.js

This pull request is supposed to fix issues with more than 92 characters in the same font (see #165). The solution is to embed the font multiple times into a pdf - each with a different cmap to transform unicodes to actual font glyphs.
I make it a pull request, so people can discuss the solution.
Credits go also to @SteffiPeTaffy, @birgitta410 and @hgsy.
@bpampuch What do you think?

Embed fonts multiple times to allow more than 92 characters.

---

src/documentContext.js

Its seem I didn't save the context properly on absolutePostinion element, and here is the fix.
No build files, in the pull request, for easier merge. Also I think browserify config in master is broken as I cannot find any way to build working build/pdfmake.js. It is building, and looks ok, but when loaded with requireJS (trough bower), it is totally nonfunctional.

[Detached blocks] Fix multipage table  not breaing at the end of page, when absolutePosition arguments are included

---

README.md

I was having problems with the italics style setting... the problem was the readme docs for it. The setting should be *italics* no *italic*.

fixes readme typo for italic style setting

---

src/fontWrapper.js

This commit changes `fontWrapper.js` to use the standardized `defineProperty` function instead of `__defineGetter__` which is not supported in Internet Explorer 10 and lower.

Fix IE10 issue with __defineGetter__

---

src/browser-extensions/pdfMake.js

Change conversion to byte array as second chance conversion during conversion

Fix PDF download for older browsers

---

src/printer.js

Code that devongovett considered implementing directly into pdfkit but didn't. [pdfkit issue 217](https://github.com/devongovett/pdfkit/issues/217). This makes autoprint work, and thus ```.print()``` also works. Haven't tried in IE because of missing datauri support.

Fix autoPrint in Chrome & FF by using Named OpenAction instead JS Action

---

dev-playground/public/samples/tables
src/docMeasure.js
src/styleContextStack.js
src/textTools.js
tests/textTools.js

If you have a two-column table, with a description in the first column, and currency in the second column, and if the description is very long, you could end up with the currency going from:
$12,345.67
to:
$12,
345.
67
To prevent this, add a noWrap style to the currency column: { noWrap: true, text: "$12,345.67" }

Add noWrap feature

---

src/docMeasure.js

When `DocMeasure.prototype.measureNode` receives an empty object as node pdfmake will throw an error: `Unrecognized document structure: {"_margin":null}`
I would prefer:
* ignore the empty node
* log a warning in the console
* continue and try to generate the PDF.

DocMeasure.prototype.measureNode fix empty node

---

src/browser-extensions/pdfMake.js

If you load pdfmake in IE8- you get an error on the page because it doesn't provide `Object.keys`. While I don't propose that pdfmake should support these legacy browsers (!) it would be great if simply loading the file didn't cause them to throw a Javascript error, stopping all other Javascript execution.
While it would be easy to have pdfmake included with conditional comments if it were being loaded as a single file, that isn't so easy where concatenation of libraries is used. This little change just sidesteps it.

Don't create pdfmake object if browser doesn't support required APIs

---

src/printer.js

This is to allow automatic testing of pdf generation via its hash sum. Having a non fixed value for creation date will make it impossible to grant a constant hash for the same pdf file.

Allow to specify CreationDate property so its possible to automatic test pdf generation

---

src/docMeasure.js

Hey,
When a table row have an undefined cell, 
``` if (!data._span) { ``` produce an exception.
When you have a lot of array in a pdf, it s totaly insame to debug it.
I suggest to catch it and throw some information to help the dev to debug that.

Catch malformed row error

---

composer.json

Due to the importance and great use of this library, I believe that it should also be available in Packagist ([Composer] (https://getcomposer.org) dependencies manager) and not only in the [NPM](https://www.npmjs.com) as usual.
If accepted my Pull Request, I will send the configuration data to enable webhook to keep the library always updated with this original repository.
Thank you for the commitment to keep this active project. =)

Add composer.json to maintain support at Packagist repository

---

src/textTools.js

The Text variable hasn’t been verified to have content. If it doesn’t PDFMake breaks and nothing is done. We are creating a conditional before trying to replace: if the variable hasn’t been defined or is undefined we proceed to place an empty String as to avoid further processing issues, if it is defined, then we proceed to replace the string as usual.
This caused entire PDFs to break its creation.

Validate Text before replacing

---

src/tableProcessor.js
tests/tableProcessor.js

fix for issues #450, #158
Fix bugs in table fillColor and draw horizontal line if is `dontBreakRows` enabled.

Table fix - dontBreakRows and fillColor

---

src/fontProvider.js

Can use *.ttc fonts now.
For example:
```js
var fonts = {
// use normal fonts
Roboto: {
normal: 'fonts/Roboto-Regular.ttf',
bold: 'fonts/Roboto-Medium.ttf',
italics: 'fonts/Roboto-Italic.ttf',
bolditalics: 'fonts/Roboto-Italic.ttf'
},
// use fonts in colleciton
PingFangSC: {
normal: ['fonts/pingfang.ttc', 'PingFangSC-Regular'],
bold: ['fonts/pingfang.ttc', 'PingFangSC-Semibold'],
}
};
var PdfPrinter = require('../src/printer');
var printer = new PdfPrinter(fonts);
var fs = require('fs');
var docDefinition = {
content: [
'First paragraph',
'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
],
defaultStyle: {
font: 'PingFangSC',
fontSize: 12
}
};
var pdfDoc = printer.createPdfKitDocument(docDefinition); …
```

Add support for TrueType Collection (.ttc)

---

src/browser-extensions/pdfMake.js
src/printer.js
tests/printer.js

I want to resolve #837 by adding an optional progress callback to `PdfPrinter.createPdfKitDocument`. The callback is called with the current progress every time an item is rendered into the pdfKitDoc.

feat (printer) Add progress callback option

---

src/elementWriter.js
tests/pageElementWriter.js

This should fix #855 - an issue where blank pages are rendered if an image can not fit vertically on a page. If the page is empty, it will add the oversized image. If there is anything already on the page, it will add add a new page containing the oversized image.

Allow oversized images if they are the only item on a page

---

src/styleContextStack.js
src/textTools.js
tests/textTools.js

Added the possibility to add a leading indent to do:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget tempor 
mi. Ut cursus velit iaculis, posuere est eu, suscipit diam. Vivamus sed dui 
convallis, ultrices nulla quis, molestie velit. Proin consectetur accumsan eros. 
Nunc in efficitur sem. Donec sit amet ultricies lorem, at feugiat ligula. Aliquam 
erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices 
posuere cubilia Curae; Nam tristique justo eu blandit semper. 
Proin pharetra eros magna, nec placerat felis aliquam sed. Fusce varius 
mauris vel est scelerisque gravida. Morbi tortor ante, egestas in tortor eu, 
iaculis ultrices tellus. 
```

Added leading indent

---

src/docMeasure.js
src/documentContext.js
tests/integration/columns.js

Page breaks aren't inserted correctly after elements with 0 columns.
Also fix calculation resulting in negative widths with 0 columns.

Fix rendering after an empty list of columns

---

src/textTools.js
tests/textTools.js

Added optional argument to text blocks to prevent leading spaces from being trimmed (issue #558).
Please let me know if there is something to change.

Added an option to preserve leading whitespaces (issue #558)

---

.gitmodules
gulpfile.js
package.json
src/browser-extensions/pdfMake.js
webpack.config.js

Hi @bpampuch,
I've got a problem with [file-saver](https://github.com/eligrey/FileSaver.js) third-party library. Unfortunately it doesn't clone at all with whole repo. So I decided to add this library as `devDependencies` in `package.json`. I think this approach is more appropriate in this instance.
Fixes list:
- Install [file-saver](https://github.com/eligrey/FileSaver.js)
- Replace `var FileSaver = require('../../libs/FileSaver.js/FileSaver');` -> `var FileSaver = require('file-saver');` for more info, please follow [this link](http://take.ms/iRVZB)
- Sorted `package.json`
- Fix some typos

FileSaver.js Fix

---

README.md
src/layoutBuilder.js
tests/layoutBuilder.js

It adds the possibility to use the page size to define the background. Also improve dynamic header/footer tests and add dynamic background test
As example, it allows to implement a page border independent of the page size or orientation like below:
```javascript
const borderMargin = 10
var dd = {
background: function(curr, size) {
return { canvas: [{ 
type: 'rect', 
x: borderMargin, 
y: borderMargin, 
w: size.width - borderMargin * 2, 
h: size.height - borderMargin * 2 
}]
}
},
content: [
'Text on Protrait',
{text: 'Text on Landscape', pageOrientation: 'landscape', pageBreak: 'before'},
{text: 'Text on Landscape 2', pageOrientation: 'portrait', pageBreak: 'after'},
'Last Page on Protrait'    
],
pageSize: 'A6'
}
```
In the definition above, all pages will have the same border. Changing …

Pass pageSize as second argument to background handler

---

dev-playground/public/index.html
dev-playground/server.js

Fixes #1202 
Evaluates definition in server instead of in client. This prevents the data loss occurred when data is serialized in POST request.

Allow to document definition with functions in playground

---

gulpfile.js
package.json
webpack.config.js
yarn.lock

Minification, source map generation and banner are handled by webpack
Advantages:
- Proper source map generation allowing to use tools like [source map explorer](https://www.npmjs.com/package/source-map-explorer) to evaluate file size culprits
- Reduce number of dependencies
- Makes easier an eventual migration to webpack 4 (webpack-stream does not support webpack 4)

Move build steps from gulp to webpack

---

src/browser-extensions/virtual-fs.js

Currently if a binary data (e.g. ArrayBuffer instance) is registered in pdfmake.vfs it works by accident
The parameter 'base64' is passed to Buffer constructor which pass down, inside Buffer implementation, to a Uint8Array constructor as the byteOffset. Luckily seems that Uint8Array constructor works in this case but could not
This PR checks for content type when creating vfs buffer so ensure no incorrect param is passed down

Explicitly allows to register binary data in virtual file system

---

src/textTools.js
tests/textTools.js

Also, cleaned up order of options in `if` check to check the cheapest expression first.

Add ability to preserve trailing white space

---

dev-playground/server.js

'rootDir' is assigned a value but never used.

 [no-unused-vars]

---

examples/tables.js
src/tableProcessor.js

Hello there,
I added a feature to set the table border color per cell. The h-/vLineColor callback is now returning the current row, node and col.
I also implemented a way to set the border color like the borders property. So you can add borderColor to the cell like
```
borderColor = ["#ff00ff", "#00ff00", "#ff00ff", "#00ff00"]
```
The current logic will prefer the border colors of the above or the cell left of the current cell. So if the left cell set the right border to blue, and the current to yellow, the border will be blue. As fallback, the current callback function will be used. To use the color of the current cell, you can set the right border of the cell before to null.

added capability to set table border color by cell

---

src/browser-extensions/virtual-fs.js

Fix loading standard fonts in browser
Standard Fonts ('afm') do not load in browser.
After some research I figured out that the main problem is that the virtual file system adapter for the browser does not implement all required functionalities.
`pdfmake` load the standard font by following code:
```js
STANDARD_FONTS = {
"Courier": function() {
return fs.readFileSync(__dirname + "/../font/data/Courier.afm", 'utf8');
},
```
`fs.readFileSync("path")` returns a buffer while `fs.readFileSync("path", 'utf8')` returns a string.
But the browser adapter only implements `fs.readFileSync("path")` so it returns a buffer and the `AFMFont.parse` fails.
Extend readFileSync(); by missing `option` argument.
https://github.com/blikblum/pdfmake-utils/issues/1

fix loading standard fonts in browser

---

examples/relative.js
src/documentContext.js
src/layoutBuilder.js
tests/documentContext.js
tests/layoutBuilder.js

I tried to position centered items relatively in table cells and the layout messed up.
I found out that the root cause was that DocumentContext updated availableWidth property based on page size, not on the width of the cell. If you are using relative positioning in a full width context it's working fine, but in a table cell it's buggy.
I've added an example to relative.js too, you can try it with and without my fix.
Should you have any suggestion don't hesitate to ask, I will make the necessary changes quickly, so that you can merge it as soon as possible.

Fix relative positioning

---

webpack.config.js

Starting from pdfkit 0.9.1 is not necessary to replace fontkit fs variable on build

Do not replace fontkit fs on build

---

src/layoutBuilder.js
src/printer.js

This is a fix proposal for Issue #1917.
Opacity attributes are used in test conditions like: `opacity = opacity || <default_value>;` .
So, for any opacity set to 0, the Boolean conversion of zero into a `false` causes `opacity` to be set to `<default_value>`.
The fix consists in checking that opacity attributes are numbers with call of the `isNumber` helper in the test condition such as : `opacity = isNumber(opacity) ? opacity : <default_value>;`
The patch has been done using the `0.1` branch as it is the stable branch. Please let me know if you prefer a path based on the `master` branch.

Colors with opacity at zero to be fully transparent

---

src/LayoutBuilder.js
src/Renderer.js

Hi Libor,
Further to your comment in PR #1918, please find a new PR with a branch based upon master to fix Issue #1917. 
Like for the previous PR, I tested with the example provided in the Issue.
Performed following operations:
- Ran the test suite: `npm run test`
- Ran dev-playground locally (`nodemon ./dev-playground/server.js`).
- Tested built `pdfmake.js` lib for test in a browser.
Please note that with the current master HEAD (prior my changes), I was not able to test in a browser with a rendering in an iframe (copy /paste code from the [pdfmake docs.](https://pdfmake.github.io/docs/getting-started/client-side/methods/)).
I used instead `pdfMake.createPdf(docDefinition).download();` which still works. I don't think it is a  issue from my setup because it works with a `pdfmake.js` lib …

Colors with opacity at zero now fully transparent

---

examples/images.js
src/Renderer.js

Thank you for great library.
Based on  #1906, I created PR.
It support cover option for image element.
It's a little different from this ticket, but it's used like this.
```
{
image: "coverImage", 
cover: {width:  300, height: 150, valign: "bottom", align: "center" }  
}
```
Unit tests have passed. 
Please let us know if you have any other work for merge.
Thanks.

support cover for image element

---

src/layoutBuilder.js
tests/layoutBuilder.js

The same fix but for v0.1.
creating Set is the same
I also check length of arguments in functions and if no functions are used, the arrays will not be evaluated.
Please check and pull. It will be great if you make release becouse I use this lib

Performance problem when pageBreakBefore for large files used fixed (v0.1)

---

src/LayoutBuilder.js

I've fixed the problematic line with creating Set that is better in performance.
Before for 300 page document algorithm spends about minute on this line every page so ~300 minutes.
Now it takes milliseconds.
Try it and pull.
Thank you, i love this library

Performance problem when pageBreakBefore for large files used fixed

---

dev-playground/server.js

- this should provide a fix for the open vulnerability issue https://security.snyk.io/vuln/SNYK-JS-PDFMAKE-3160329
- replaced the `eval` with the `function` call

Vulnerability fix

---

examples/qrCode.js
src/qrEnc.js

I have add padding option of qrcode for set qrcode padding.
User can set option of qrcode with `padding` field following example below.
```
{ qr: "my message", fit: 150, padding: 1 }
```
Output:

feat: add padding option of qrcode for set qrcode padding.

---

src/DocMeasure.js
tests/unit/DocMeasure.spec.js

This pull request fixes issues [#875](https://github.com/bpampuch/pdfmake/issues/875) and [#2582](https://github.com/bpampuch/pdfmake/issues/2582) by not increasing the counter of the list marker when list item is a list (nested list)

Fixes #875 and #2582

---

src/styleContextStack.js
tests/styleContextStack.js

Speed up StyleContextStack.autopush() for large tables by skipping slower creation of styleOverrideObject and just using the item itself.
Three tests are updated to handle the change in behavior.
Implements #2732

Speed up StyleContextStack.autopush() for large tables

---

src/DocumentContext.js
src/LayoutBuilder.js
tests/unit/DocumentContext.spec.js

Fixes all the issues below, it is just one bug though. The problem was that it was not storing the correct context in the ending cell of a row span when there were nested column groups (columns or tables). Now the reference to the ending cell is not stored in the DocumentContext but in the first cell that started the row span, this way we can after check if the current cell is just the cell after a row span and thus store the current context in the ending cell.
[#2069](https://github.com/bpampuch/pdfmake/issues/2069)
[#2189](https://github.com/bpampuch/pdfmake/issues/2189)
[#1545](https://github.com/bpampuch/pdfmake/issues/1545)
[#668](https://github.com/bpampuch/pdfmake/issues/668)
[#997](https://github.com/bpampuch/pdfmake/issues/997) …

Fixes issues 2069 2189 1545 668 997 1654

---

src/DocumentContext.js
src/LayoutBuilder.js
tests/unit/LayoutBuilder.spec.js

Fixes issue [#371](https://github.com/bpampuch/pdfmake/issues/371)
When there was a page break in a column group it was not taking into consideration the 'y' of the cells that did not produce a page break. Now it takes into consideration all the cells even if they don't break page, this way we get the correct value for variable 'prevY' of the page break.

Fixes issue #371

---

src/ElementWriter.js
src/TableProcessor.js

Fixes issue [#1836](https://github.com/bpampuch/pdfmake/issues/1836)
The problem was that fillColor items of unbreakable blocks were not being added at the beginning of the body items array like any other fillColor items.

Fixes issue 1836

---

src/DocumentContext.js
src/LayoutBuilder.js
tests/unit/LayoutBuilder.spec.js

Fixes [#1042](https://github.com/bpampuch/pdfmake/issues/1042)
It was not calculating correctly the 'y' at the end of a rowSpan with dontBreakRows.

Fixes issue #1042

---

src/LayoutBuilder.js
tests/unit/LayoutBuilder.spec.js

Fixes issues [#1006](https://github.com/bpampuch/pdfmake/issues/1006) and [#2748](https://github.com/bpampuch/pdfmake/issues/2748)
Now margins (top/bottom) of nodes and row height are considered for breaking page

Fixes issues #1006 and #2748

---

src/DocumentContext.js
src/LayoutBuilder.js

- Fixes [#2783](https://github.com/bpampuch/pdfmake/issues/2783), now margins of nodes with relativePosition or absolutePosition are ignored and don't interfere with the regular flow of the layout.
- Fixes [#1943](https://github.com/bpampuch/pdfmake/issues/1943) [#1509](https://github.com/bpampuch/pdfmake/issues/1509) [#2017](https://github.com/bpampuch/pdfmake/issues/2017) and [#2298](https://github.com/bpampuch/pdfmake/issues/2298): They are all the same bug, the problem was that when a page break was produced and there was a snapshot stored (columns or tables; detached blocks also generate a snapshot but since we are ignoring their margins now, no need to do anything), it was calculating the new available width of the top parent snapshot without taking into consideration the lateral …

Fixes issues #2783 #1943 #1509 #2017 and #2298

---

src/DocumentContext.js
src/LayoutBuilder.js
tests/unit/LayoutBuilder.spec.js

Fixes issues [#928](https://github.com/bpampuch/pdfmake/issues/928) [#2121](https://github.com/bpampuch/pdfmake/issues/2121) [#2720](https://github.com/bpampuch/pdfmake/issues/2720) and [#921](https://github.com/bpampuch/pdfmake/issues/921). There was a problem with how page breaks provoked by cells with rowspan were handled.
Fixes issue: [#2799](https://github.com/bpampuch/pdfmake/issues/2799): It was trying to find if previous cell started a row span without taking into consideration that column index was increased by col span cells. Method call has been moved before column index has been increased by col span cells
Also fixes PR [#2771](https://github.com/bpampuch/pdfmake/pull/2771): The idea to implement the issue was correct, the implementation was not because some wrong assumptions …

Fixes issues 928 2121 2720 921\n\nFixes issue 2799\n\nFixes PR 2778
